export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'
export const ADD_EVENT = 'ADD_EVENT'
export const ALLDELETE_EVENT = 'ALLDELETE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const SANBAI = 'SANBAI'
export const SANBAITAS = 'SANBAITAS'